### ISSUE TITLE
CSS də kod yazmaq

### ISSUE THREAD

**Issue by EldanizAkbar** [GenceviMustafa/PragmatechFoundationProject#1]
https://github.com/GenceviMustafa/PragmatechFoundationProject/blob/938078039aac76f61b3856cacc72fef07213e30f/Tasks/week02-day5/css/style.css#L1

CSS faylındakı kodları style tag-inin içərisində yazmağa ehtiyac yoxdu.

**Comment by GenceviMustafa** [comment]
Tamam aydindi
